name: Contribution Snake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # 使用 PAT 进行 checkout 认证
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Generate Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/contribution-snake.svg
            assets/contribution-snake-dark.svg?palette=github-dark
          # 显式传递 PAT 到 snk 动作
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Push to GitHub
        # 尝试升级到最新版本或指定更稳定的版本
        uses: EndBug/add-and-commit@v10
        with:
          branch: main
          message: "chore: generate contribution snake"
          add: .
          push: true
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
